export const BOOK_TRENDING_LIST_REQUEST = 'BOOK_TRENDING_LIST_REQUEST';
export const BOOK_TRENDING_LIST_SUCCESS = 'BOOK_TRENDING_LIST_SUCCESS';
export const BOOK_TRENDING_LIST_FAIL = 'BOOK_TRENDING_LIST_FAIL';

export const BOOK_DESCRIPTION_REQUEST = 'BOOK_DESCRIPTION_REQUEST';
export const BOOK_DESCRIPTION_SUCCESS = 'BOOK_DESCRIPTION_SUCCESS';
export const BOOK_DESCRIPTION_FAIL = 'BOOK_DESCRIPTION_FAIL';

export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL';
export const BOOK_LIST_RESET = 'BOOK_LIST_RESET';
