export const BOOK_TRENDING_LIST_REQUEST = 'BOOK_TRENDING_LIST_REQUEST';
export const BOOK_TRENDING_LIST_SUCCESS = 'BOOK_TRENDING_LIST_SUCCESS';
export const BOOK_TRENDING_LIST_FAIL = 'BOOK_TRENDING_LIST_FAIL';
