export const BOOK_TRENDING_LIST_REQUEST = 'BOOK_TRENDING_LIST_REQUEST';
export const BOOK_TRENDING_LIST_SUCCESS = 'BOOK_TRENDING_LIST_SUCCESS';
export const BOOK_TRENDING_LIST_FAIL = 'BOOK_TRENDING_LIST_FAIL';

export const BOOK_DESCRIPTION_REQUEST = 'BOOK_DESCRIPTION_REQUEST';
export const BOOK_DESCRIPTION_SUCCESS = 'BOOK_DESCRIPTION_SUCCESS';
export const BOOK_DESCRIPTION_FAIL = 'BOOK_DESCRIPTION_FAIL';

export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL';
export const BOOK_LIST_RESET = 'BOOK_LIST_RESET';

export const BOOK_CREATE_REQUEST = 'BOOK_CREATE_REQUEST';
export const BOOK_CREATE_SUCCESS = 'BOOK_CREATE_SUCCESS';
export const BOOK_CREATE_FAIL = 'BOOK_CREATE_FAIL';
export const BOOK_CREATE_RESET = 'BOOK_CREATE_RESET';

export const BOOK_DELETE_REQUEST = 'BOOK_DELETE_REQUEST';
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS';
export const BOOK_DELETE_FAIL = 'BOOK_DELETE_FAIL';
export const BOOK_DELETE_RESET = 'BOOK_DELETE_RESET';

export const BOOK_UPDATE_REQUEST = 'BOOK_UPDATE_REQUEST';
export const BOOK_UPDATE_SUCCESS = 'BOOK_UPDATE_SUCCESS';
export const BOOK_UPDATE_FAIL = 'BOOK_UPDATE_FAIL';
export const BOOK_UPDATE_RESET = 'BOOK_UPDATE_RESET';
